//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiGame_SP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiplayerGame
    {
        public int Id { get; set; }
        public string gameId { get; set; }
        public string userId1 { get; set; }
        public string userId2 { get; set; }
        public string winner { get; set; }
        public string startPage { get; set; }
        public Nullable<int> points { get; set; }
        public int timeElapsed { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> dateOfGame { get; set; }
    }
}
